
server:
  port: '${GDG_SERVER_PORT:8080}'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  server:
    address: '127.0.0.1'
    port: '9001'

spring:
  application:
    name: '@project.name@'
  cloud:
    gcp:
      logging:
        enabled: 'true'    

---

gdg:
  proxy:
#    url: '${GDG_PROXY_URL:http://localhost:8090}'
    url: 'http://localhost:8090'
  message:
    topic: '${GDG_MESSAGE_TOPIC:testTopic}'
    subscription: '${GDG_MESSAGE_SUBSCRIPTION:testSubscription}'
